//Generic Dimension
// ignore_for_file: constant_identifier_names

const MARGIN_SMALL = 4.0;
const MARGIN_MEDIUM = 8.0;
const MARGIN_CARD_MEDIUM_2 = 12.0;
const MARGIN_MEDIUM_2x = 16.0;
const MARGIN_MEDIUM_3x = 20.0;

const MARGIN_LARGE = 24.0;
const MARGIN_XLARGE = 32.0;
const MARGIN_XXLARGE = 48.0;

const TEXT_SMALL = 8.0;
const TEXT_SMALL_2x = 12.0;
const TEXT_REGULAR = 14.0;
const TEXT_REGULAR_2x = 16.0;
const TEXT_REGULAR_3x = 20.0;
const TEXT_HEADING = 24.0;
const TEXT_HEADING_2X = 28.0;
const TEXT_BIG = 32.0;

//app specific
const APPBAR_ELEVATION = 0.0;
const APPBAR_HEIGHT = 80.0;
const SEARCH_BAR_BORDER_RADIUS = 12.0;
const CAROUSEL_SECTION_HEIGHT = 200.0;
const CAROUSEL_CARD_HEIGHT = 200.0;
const TAB_BAR_HEIGHT = 30.0;
const HORIZONTAL_BOOK_LIST_VIEW_HEIGHT = 170.0;
const BOOK_ITEM_WIDTH = 100.0;
const BOOK_LIST_ITEM_HEIGHT = 70.0;
const BOOK_SHELVES_COLLECTION_HEIGHT = 50.0;

const RATING_BIG_TEXT_SIZE = 64.0;


const SHELVES_DETAILS_PAGE_TITLE_SECTION_HEIGHT = 120.0;

const BOOK_DETAILS_TITLE_SECTION_HEIGHT = 150.0;
const BOOK_DETAILS_RATING_AND_INFO_SECTION_HEIGHT = 50.0;

const BOOK_BOTTOM_MODAL_TITLE_HEIGHT = 100.0;
const BOOK_BOTTOM_MODAL_LISTTILE_HEIGHT = 50.0;

const CREATE_NEW_SHELVES_BUTTON_WIDTH = 150.0;
const CREATE_NEW_SHELVES_BUTTON_HEIGHT = 50.0;

const USER_COMMENT_SECTION_HEIGHT = 150.0;

const EMPTY_VIEW_WIDTH = 200.0;
const EMPTY_VIEW_HEIGHT = 200.0;