// ignore_for_file: constant_identifier_names

const String KEY_CAROUSEL_SECTION = 'KEY_CAROUSEL_SECTION';
const String KEY_BOOK_MORE_LIST_VIEW = 'KEY_BOOK_MORE_LIST_VIEW';
const String KEY_BOOK_COLLECTION_DETAILS_PAGE_BACK_BUTOON =
    'KEY_BOOK_COLLECTION_DETAILS_PAGE_BACK_BUTOON';
const String KEY_DETAILS_PAGE_IMAGE = 'KEY_DETAILS_PAGE_IMAGE';
const String KEY_DETAILS_PAGE_TITLE = 'KEY_DETAILS_PAGE_TITLE';
const String KEY_DETAILS_PAGE_AUTHOR = 'KEY_DETAILS_PAGE_AUTHOR';
const String KEY_DETAILS_PAGE_TITLE_AND_AUTHOR_SECTION =
    'KEY_DETAILS_PAGE_TITLE_AND_AUTHOR_SECTION';
const String KEY_BOOK_DETAILS_PAGE_BACK_BUTOON =
    'KEY_BOOK_DETAILS_PAGE_BACK_BUTOON';
const String KEY_CAROUSEL_ITEM = 'KEY_CAROUSEL_ITEM';
const String KEY_SEARCH_TEXT_FIELD = 'KEY_SEARCH_TEXT_FIELD';
const String KEY_SEARCH_RESULT_BOOK_VIEW = 'KEY_SEARCH_RESULT_BOOK_VIEW';
const String KEY_SEARCH_SUGGEST_BOOK_LIST = 'KEY_SEARCH_SUGGEST_BOOK_LIST';
const String KEY_SEARCH_ICON_BUTTON = 'KEY_SEARCH_ICON_BUTTON';
const String KEY_SEARCH_PAGE_BACK_BUTTON = 'KEY_SEARCH_PAGE_BACK_BUTTON';

const String KEY_HOME_PAGE_BOTTOM_NAVIAGATION_BAR_HOME =
    'KEY_HOME_PAGE_BOTTOM_NAVIAGATION_BAR_HOME';
const String KEY_HOME_PAGE_BOTTOM_NAVIAGATION_BAR_LIBRARY =
    'KEY_HOME_PAGE_BOTTOM_NAVIAGATION_BAR_LIBRARY';

const String KEY_TAB_BAR_YOUR_LIBRARY = 'KEY_TAB_BAR_YOUR_LIBRARY';
const String KEY_TAB_BAR_YOUR_SHELF = 'KEY_TAB_BAR_YOUR_SHELF';

const String KEY_RESUABLE_BOOK_LIST = 'KEY_RESUABLE_BOOK_LIST';

const String KEY_CHANGE_VIEW_BUTTON = 'KEY_CHANGE_VIEW_BUTTON';
const String KEY_RESUABLE_LISTVIEW = 'KEY_RESUABLE_LISTVIEW';
const String KEY_RESUABLE_GRIDVIEW_LARGE = 'KEY_RESUABLE_GRIDVIEW_LARGE';
const String KEY_RESUABLE_GRIDVIEW_SMALL = 'KEY_RESUABLE_GRIDVIEW_SMALL';

const String KEY_YOUR_BOOK_VIEW_BOOK_LIST_ITEM = 'KEY_YOUR_BOOK_VIEW_BOOK_LIST_ITEM';
const String KEY_SEE_MORE_BUTTON = 'KEY_SEE_MORE_BUTTON';

const String KEY_BOOK_MORE_MODAL_BOTTOM = 'KEY_BOOK_MORE_MODAL_BOTTOM';
const String KEY_ADD_TO_SHELF = 'KEY_ADD_TO_SHELF';

const String KEY_CONFIRM_ADD_NEW_SHELF = 'KEY_CONFIRM_ADD_NEW_SHELF';
const String KEY_ADD_NEW_SHELF_TEXT_FIELD = 'KEY_ADD_NEW_SHELF_TEXT_FIELD';

const String KEY_SHELF_LIST_VIEW = 'KEY_SHELF_LIST_VIEW';

const String KEY_SHELF_BOOK_LIST_VIEW = 'KEY_SHELF_BOOK_LIST_VIEW';

const String KEY_SHELF_DETAILS_PAGE_BACK_BUTTON = 'KEY_SHELF_DETAILS_PAGE_BACK_BUTTON';

const String KEY_SHELF_DETAILS_POPUP_MENU_BUTTON = 'KEY_SHELF_DETAILS_POPUP_MENU_BUTTON';
const String KEY_SHELF_DETAILS_RENAME = 'KEY_SHELF_DETAILS_RENAME';
const String KEY_SHELF_DETAILS_DELETE = 'KEY_SHELF_DETAILS_DELETE';
const String KEY_SHELF_DETAILS_TEXT_FIELD = 'KEY_SHELF_DETAILS_TEXT_FIELD';

const String KEY__SHELF_DELETE_ALERT_DIALOG = 'KEY__SHELF_DELETE_ALERT_DIALOG';
const String KEY__SHELF_DELETE_ALERT_DIALOG_CONFIRM = 'KEY__SHELF_DELETE_ALERT_DIALOG_CONFIRM';